export {default as HomeP} from './Home_page'
export {default as LoginP} from './Login_page'
export {default as SignupP} from './Signup_page'
export {default as ResetPwdP} from './Forget_password_page'
export {default as AdminP} from './Admin'
export {default as UserProfileP} from './UserProfile'